coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        target: auto
        informational: true
    patch:
      default:
        target: auto
        informational: true

ignore:
  - "tests/**"
  - "benches/**"
  - "examples/**"

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
