//! Core type primitives for the Anamnesis graph engine.

/// Unique identifier for a graph node.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct NodeId(pub u64);

/// Unique identifier for a graph edge.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct EdgeId(pub u64);

/// Stable identifier for the peer (human or agent) that produced a knowledge
/// fragment, stored in every node's [`Origin`](super::node::Origin).
///
/// Newtypes over `u64` — same pattern as `NodeId` and `EdgeId`.
/// Type-safe: a `PeerId` cannot be used where a `NodeId` is expected.
/// Production always stamps `PeerId(0)`; the field is retained for provenance
/// and identity-prior stamping (`agent_id` search bias) without a registry.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct PeerId(pub u64);

/// The kind of source that produced a knowledge fragment.
///
/// Consumers set this explicitly on [`Origin`](super::node::Origin); the engine
/// never auto-classifies.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum SourceKind {
    /// Observation made by an automated agent during a session.
    AgentObservation,
    /// Direct input from a human (typed message, annotation, etc.).
    HumanInput,
    /// Fact extracted from a document, file, or structured data source.
    DocumentExtract,
    /// Event generated by the system (tick, migration, lifecycle hook).
    SystemEvent,
    /// Derived or synthesised from existing graph nodes (no external source).
    Inferred,
    /// Imported from an external system or API.
    External,
}

/// Unix timestamp in milliseconds.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct Timestamp(pub u64);

impl Timestamp {
    /// Returns the current system time as milliseconds since Unix epoch.
    pub fn now() -> Self {
        use std::time::{SystemTime, UNIX_EPOCH};
        let millis = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .unwrap_or_default()
            .as_millis() as u64;
        Timestamp(millis)
    }
}

/// A single access trace in a node's bounded access-history window.
///
/// Each trace records both *when* it was laid down (`at`) and the per-trace decay
/// rate `d_j` (`decay`) computed once at that moment from the activation of the
/// EXISTING traces (Pavlik & Anderson 2005 activation-dependent decay,
/// dissipation.md). The base level sums each trace with its OWN decay,
/// `B_i = ln(Σ_j (now − at_j)^(−decay_j))`, so a trace laid down on a strongly
/// active node decays faster than one laid down on a cold node.
///
/// Derives mirror [`super::node::Node`] (`Debug, Clone, PartialEq`) plus `Copy`
/// since both fields are scalar; it deliberately does NOT derive `Eq`/`Hash`/`Ord`
/// because `decay` is an `f64`.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct AccessTrace {
    /// When this access trace was laid down (the event timestamp).
    pub at: Timestamp,
    /// The per-trace decay rate `d_j`, computed once at creation from the
    /// activation of the existing traces and then stored immutably with the trace.
    pub decay: f64,
}

/// Knowledge type taxonomy. `node_type` is a *policy* input to the dissipation and
/// coupling priors, not an independent dynamics knob:
/// - decay: it selects the per-type multiplier on the single free decay prior `d`
///   ([`crate::mechanics::priors::decay_multiplier_for_type`], dissipation.md) —
///   `Identity` is protected (≈0), ordinary knowledge (`Semantic`/`Custom`) decays
///   slowly, `Episodic` at the full rate;
/// - coupling: it contributes the edge-type-affinity feature to the cold-start
///   coupling seed (conductance.md). It supplies no separate decay rate or weight.
///
/// The three partitions are identity (slow-decaying self-knowledge), ordinary
/// knowledge (`Semantic`/`Custom`), and fast-decaying episodic memory. This is a
/// deliberately small policy vocabulary: only the distinctions the dissipation and
/// coupling priors actually discriminate are variants; every finer consumer label
/// rides `Custom(String)`.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum KnowledgeType {
    /// Identity / self-knowledge (merged from the former three identity tiers).
    /// Slowest decay — protected from ordinary dissipation. Legacy DBs' three
    /// identity wire strings (`identity_core`/`identity_learned`/`identity_state`)
    /// decode here, preserving their slow-decay semantics.
    Identity,

    /// Extracted fact or ordinary knowledge from conversation or document.
    /// Moderate decay.
    Semantic,

    /// Raw conversation turn or session text. Fast decay (full nominal rate).
    Episodic,

    /// Consumer-defined type. Carries any label outside the fixed policy
    /// vocabulary (including the wire strings of variants removed in the 0.10.0
    /// shrink, which decode here via the storage compat fallback). Decays at the
    /// ordinary-knowledge rate.
    Custom(String),
}

/// Explicit memory tier override for a node.
///
/// When set to anything other than `Auto`, the tier overrides the natural
/// salience-based tier assignment. `Core` nodes are protected from decay.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Default)]
pub enum MemoryTier {
    /// No override — tier is determined by salience range (default).
    #[default]
    Auto,
    /// Pinned to core memory — protected from decay.
    Core,
    /// Pinned to recall tier — moderate decay.
    Recall,
    /// Pinned to archival tier — fast decay.
    Archival,
}

/// Edge type — determines the within-row propagation factor during spreading
/// activation. The factor itself is the calibrated `edge_type_factor` prior
/// ([`crate::mechanics::priors::edge_type_factor`]); the type only names the
/// relation.
///
/// Supportive edges propagate activation. `Contradicts` is excluded from propagation
/// and instead surfaces query-local frustration stress between its active endpoints
/// (frustration.md / ADR-0006) — it is never inhibitory damping.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum EdgeType {
    // Supportive (propagation)
    /// Conceptual relationship.
    Semantic,
    /// Cause-effect relationship.
    Causal,
    /// Temporal sequence.
    Temporal,
    /// Decision rationale.
    Reason,
    /// Repeated confirmation.
    ReinforcedBy,
    /// Derived from multiple fragments.
    ConsolidatedFrom,
    /// Derived knowledge to source episode.
    ExtractedFrom,
    /// Shared entity link across agents.
    Entity,
    /// Replaces outdated knowledge (directional: strong toward new, weak toward old).
    Supersedes,
    /// Considered and discarded option.
    RejectedAlternative,
    /// Positive evidential support.
    Supports,
    /// Refuting evidence. Weak supportive propagation, not inhibitory.
    Refutes,
    /// Hierarchical or containment relationship.
    BelongsTo,

    // Constraint (excluded from propagation; surfaces frustration stress)
    /// Conflicting assertions. Excluded from propagation; surfaces query-local
    /// frustration stress when both endpoints are active (ADR-0006), never deleted.
    Contradicts,

    /// Consumer-defined edge type.
    Custom(String),
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn node_id_is_copy() {
        let id = NodeId(42);
        let id2 = id; // Copy
        assert_eq!(id, id2);
    }

    #[test]
    fn edge_id_is_copy() {
        let id = EdgeId(7);
        let id2 = id;
        assert_eq!(id, id2);
    }

    #[test]
    fn timestamp_ordering() {
        let t1 = Timestamp(100);
        let t2 = Timestamp(200);
        assert!(t1 < t2);
    }

    #[test]
    fn all_knowledge_types_constructable() {
        let types = [
            KnowledgeType::Identity,
            KnowledgeType::Semantic,
            KnowledgeType::Episodic,
            KnowledgeType::Custom("my-type".to_string()),
        ];
        assert_eq!(types.len(), 4);
    }

    #[test]
    fn all_edge_types_constructable() {
        let types = vec![
            EdgeType::Semantic,
            EdgeType::Causal,
            EdgeType::Temporal,
            EdgeType::Reason,
            EdgeType::ReinforcedBy,
            EdgeType::ConsolidatedFrom,
            EdgeType::ExtractedFrom,
            EdgeType::Entity,
            EdgeType::Supersedes,
            EdgeType::RejectedAlternative,
            EdgeType::Supports,
            EdgeType::Refutes,
            EdgeType::BelongsTo,
            EdgeType::Contradicts,
            EdgeType::Custom("my-edge".to_string()),
        ];
        assert_eq!(types.len(), 15);
    }
}
