import {createHash,randomBytes,randomUUID} from 'node:crypto';
import {mkdir,readFile,writeFile,rm,chmod} from 'node:fs/promises';
import {join} from 'node:path';
import {spawn} from 'node:child_process';
import {DREAM_GDS_IMAGE,DREAM_GDS_VERSION,DREAM_ALGORITHM,DREAM_NETWORK,type DreamLeidenAdapter,type DreamLeidenInput} from '../../packages/core/src/dream-leiden-adapter.ts';
const IMAGE='neo4j@sha256:037cf5756f0135cbfd66b739b6df7c7c4bb100f9ce11602f6f9538e17e02c74d';
const JAR_SHA='246e3fbbbf733b4def1e7b0a9740a2309f6605ee8a7b46b29fe1de56d0a4b47c';
const run=(args:string[],input='',extraEnv:Record<string,string>={})=>new Promise<{code:number|null,out:string,err:string}>((resolve,reject)=>{const p=spawn('docker',args,{env:{...process.env,...extraEnv,DOCKER_HOST:process.env.DOCKER_HOST??'unix:///Users/ino/.colima/default/docker.sock'},stdio:['pipe','pipe','pipe']});let out='',err='';const cap=8*1024*1024;const bounded=(target:'out'|'err')=>(b:Buffer)=>{if((target==='out'?out:err).length+b.length>cap){p.kill('SIGKILL');return}if(target==='out')out+=b;else err+=b};p.stdout.on('data',bounded('out'));p.stderr.on('data',bounded('err'));p.once('error',reject);p.once('close',(code)=>resolve({code,out,err}));p.stdin.end(input);});
function csv(text:string){return text.trim().split(/\r?\n/).slice(1).filter(Boolean).map(x=>x.split(',').map(v=>v.trim()));}
export function createDreamLeidenAdapter(): DreamLeidenAdapter|undefined {
 const assets=process.env.ANAMNESIS_DREAM_GDS_ASSETS, work=process.env.ANAMNESIS_DREAM_GDS_WORK;
 if(!assets||!work) return undefined;
 return {execute:async(input:DreamLeidenInput)=>{const manifest=JSON.parse(await readFile(join(assets,'admission.json'),'utf8'));if(manifest.jar.sha256!==JAR_SHA||manifest.pins.image!==IMAGE||manifest.pins.gdsVersion!==DREAM_GDS_VERSION)throw new Error('dream_adapter_untrusted');
  const jar=await readFile(join(assets,'neo4j-graph-data-science-2.13.12.jar'));if(createHash('sha256').update(jar).digest('hex')!==manifest.jar.sha256||manifest.jar.sha256!==JAR_SHA)throw new Error('dream_adapter_untrusted');
  const id=`dream-${randomUUID()}`, dir=join(work,id), password=randomBytes(24).toString('hex');await mkdir(join(dir,'plugins'),{recursive:true,mode:0o755});await writeFile(join(dir,'plugins','neo4j-graph-data-science-2.13.12.jar'),jar);await chmod(join(dir,'plugins','neo4j-graph-data-science-2.13.12.jar'),0o444);await writeFile(join(dir,'auth.env'),`NEO4J_AUTH=neo4j/${password}\nNEO4J_server_http_enabled=false\nNEO4J_server_https_enabled=false\nNEO4J_dbms_security_procedures_unrestricted=gds.*\nNEO4J_dbms_security_procedures_allowlist=gds.*\n`,{mode:0o600});
  const name=`anamnesis-dream-${randomUUID()}`;let attach:any;
  try {const made=await run(['create','--name',name,'--hostname','dream-gds','--pull','never','--platform','linux/arm64/v8','--network','none','--restart','no','--no-healthcheck','--label','omo.task=dream-leiden-real','--label',`omo.owner=${id}`,'--env-file',join(dir,'auth.env'),'-v',`${name}-data:/data`,'-v',`${name}-logs:/logs`,'--mount',`type=bind,src=${join(dir,'plugins','neo4j-graph-data-science-2.13.12.jar')},dst=/plugins/neo4j-graph-data-science-2.13.12.jar,readonly`,IMAGE]);if(made.code!==0)throw Error('dream_container_create_failed');
   const cid=made.out.trim();attach=spawn('docker',['start','--attach',cid],{stdio:['ignore','pipe','pipe']});let logs='';let readyResolve!:()=>void,readyReject!: (e:Error)=>void;const ready=new Promise<void>((resolve,reject)=>{readyResolve=resolve;readyReject=reject});const timer=setTimeout(()=>{attach.kill('SIGKILL');readyReject(Error('dream_container_start_timeout'))},300000);const observe=(b:Buffer)=>{logs+=b.toString();if(logs.includes('Started.'))readyResolve()};attach.stdout.on('data',observe);attach.stderr.on('data',observe);attach.once('error',readyReject);attach.once('close',(code:number|null)=>{if(!logs.includes('Started.'))readyReject(Error(`dream_container_start_failed:${code}:${logs.slice(-500)}`))});await ready;clearTimeout(timer);
   const q=async(c:string)=>{const r=await run(['exec','-i','--env-file',join(dir,'auth.env'),cid,'cypher-shell','-a','bolt://127.0.0.1:7687','-u','neo4j','-d','neo4j','--format','plain','--fail-fast'],c+';\n',{NEO4J_PASSWORD:password});if(r.code!==0)throw Error('dream_query_failed');return csv(r.out)};
   const ids=input.graph.nodes; if(ids.length!==input.graph.node_count||input.graph.arcs.length!==input.graph.arc_count)throw Error('dream_graph_unverified');
   await q(`UNWIND ${JSON.stringify(ids)} AS id CREATE (:DreamNode {id:id}) RETURN count(*)`);
   for(let i=0;i<input.graph.arcs.length;i+=256){const batch=input.graph.arcs.slice(i,i+256);await q(`UNWIND ${JSON.stringify(batch)} AS e MATCH (a:DreamNode {id:e.from}),(b:DreamNode {id:e.to}) CREATE (a)-[:TRANSITION {weight:e.weight}]->(b) RETURN count(*)`)}
   const graph='dream_graph';await q(`CALL gds.graph.project('${graph}','DreamNode',{TRANSITION:{orientation:'UNDIRECTED',properties:{weight:{property:'weight',aggregation:'NONE'}}}},{readConcurrency:1,validateRelationships:true}) YIELD nodeCount,relationshipCount RETURN nodeCount,relationshipCount`);
   const procedures=await q("SHOW PROCEDURES YIELD name,signature WHERE name='gds.leiden.stream' RETURN name,signature");if(!procedures.length)throw Error('dream_leiden_unavailable');
   const rows=await q(`CALL gds.leiden.stream('${graph}', {randomSeed: 42, concurrency: 1, maxLevels: 10, tolerance: 0.0001}) YIELD nodeId, communityId RETURN gds.util.asNode(nodeId).id AS id, communityId ORDER BY id`);const assignments=rows.map(r=>({element_id:r[0]!,community_assignment:Number(r[1])}));if(assignments.length!==ids.length||new Set(assignments.map(x=>x.element_id)).size!==ids.length)throw Error('dream_result_unverified');
   await q(`CALL gds.graph.drop('${graph}') YIELD graphName RETURN graphName`);const artifact_digest=createHash('sha256').update(JSON.stringify({export_digest:input.export_digest,assignments,image_digest:DREAM_GDS_IMAGE,gds_version:DREAM_GDS_VERSION,algorithm:DREAM_ALGORITHM,network:DREAM_NETWORK})).digest('hex');return {export_digest:input.export_digest,artifact_digest,assignments,image_digest:DREAM_GDS_IMAGE,gds_version:DREAM_GDS_VERSION,algorithm:DREAM_ALGORITHM,network:DREAM_NETWORK,semantic_writes:false,deterministic:true,exit:'success'};
  } finally {await run(['rm','-f','-v',name]);await run(['volume','rm',`${name}-data`,`${name}-logs`]);await rm(dir,{recursive:true,force:true});}
 }};
}
