//! Peer identity module — PeerId, PeerProfile, TrustLevel, SourceKind, PeerRegistry.
//!
//! A "peer" is any human or agent that produces knowledge fragments ingested into
//! the graph. The registry maps stable `PeerId` values to human-readable aliases
//! and platform usernames, enabling multi-agent and multi-human knowledge graphs.

use crate::error::Error;
use crate::graph::types::PeerId;
use std::collections::HashMap;

/// Trust level assigned to a peer.
///
/// Determines the `scope_weight` bonus applied during search ranking.
/// Declared lowest-to-highest so `Ord` derives correctly (Untrusted < Owner).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub enum TrustLevel {
    /// Untrusted source — penalised in ranking. scope_weight -0.05
    Untrusted,
    /// Read-only observer — can query but not contribute. scope_weight +0.00
    Observer,
    /// Automated agent — no human in the loop. scope_weight +0.00
    Agent,
    /// Standard member — regular contributor. scope_weight +0.03
    Member,
    /// Administrative trust — can manage peers and conventions. scope_weight +0.07
    Admin,
    /// Full trust — graph owner or primary operator. scope_weight +0.10
    Owner,
}

impl TrustLevel {
    /// Returns the scope_weight bonus (positive or negative) for this trust level.
    pub fn scope_weight_bonus(&self) -> f64 {
        match self {
            TrustLevel::Owner => 0.10,
            TrustLevel::Admin => 0.07,
            TrustLevel::Member => 0.03,
            TrustLevel::Agent => 0.00,
            TrustLevel::Observer => 0.00,
            TrustLevel::Untrusted => -0.05,
        }
    }

    /// The cold-start trust reservoir (log trust-odds) this coarse level seeds.
    ///
    /// The coarse `TrustLevel` is the *prior*; evidence (corroboration / feedback)
    /// then moves the reservoir through `update_peer_trust`. A neutral `Agent`
    /// starts at `0.0` (no-evidence prior); higher levels start with a positive
    /// prior, `Untrusted` with a negative one. Units match `A_i`/`C_ij` log-odds
    /// (mechanics::priors), so the reservoir composes additively with evidence.
    pub fn prior_trust_reservoir(&self) -> f64 {
        match self {
            TrustLevel::Owner => 4.0,
            TrustLevel::Admin => 2.0,
            TrustLevel::Member => 1.0,
            TrustLevel::Agent => 0.0,
            TrustLevel::Observer => 0.0,
            TrustLevel::Untrusted => -2.0,
        }
    }
}

/// The kind of source that produced a knowledge fragment.
///
/// Consumers set this explicitly on `Origin`; the engine never auto-classifies.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum SourceKind {
    /// Observation made by an automated agent during a session.
    AgentObservation,
    /// Direct input from a human (typed message, annotation, etc.).
    HumanInput,
    /// Fact extracted from a document, file, or structured data source.
    DocumentExtract,
    /// Event generated by the system (tick, migration, lifecycle hook).
    SystemEvent,
    /// Derived or synthesised from existing graph nodes (no external source).
    Inferred,
    /// Imported from an external system or API.
    External,
}

/// Profile of a registered peer.
#[derive(Debug, Clone, PartialEq)]
pub struct PeerProfile {
    /// Stable identifier.
    pub id: PeerId,
    /// Primary display name.
    pub name: String,
    /// Trust level assigned to this peer.
    pub trust_level: TrustLevel,
    /// Evidence-updated trust reservoir in log trust-odds (social.md "Peer Trust").
    ///
    /// Authoritative trust state, same units as the `A_i`/`C_ij` reservoirs. Seeded
    /// from `trust_level.prior_trust_reservoir()` (the coarse level is the *prior*),
    /// then moved by corroboration and feedback through the single traceable update
    /// path. Its bounded projection (`mechanics::priors::project_trust`) is the
    /// readout `trust_weight` evidence term. Moving it never erases origin or the
    /// coarse level — only the evidence estimate changes.
    pub trust_reservoir: f64,
    /// Count of corroboration/feedback events that have moved `trust_reservoir`.
    /// Part of the trust trace (peer-identity.md "Trust Profile": corroboration /
    /// contradiction / feedback counts); a non-silent record that trust moved.
    pub trust_evidence_count: u64,
    /// Additional aliases (nicknames, handles).
    pub aliases: Vec<String>,
    /// Platform to username mappings (e.g. "discord" to "ino#1234").
    pub platforms: HashMap<String, String>,
}

impl PeerProfile {
    /// Create a new profile with the given name and trust level. The evidence
    /// trust reservoir is seeded from the coarse level's declared prior.
    pub fn new(id: PeerId, name: impl Into<String>, trust_level: TrustLevel) -> Self {
        Self {
            id,
            name: name.into(),
            trust_reservoir: trust_level.prior_trust_reservoir(),
            trust_evidence_count: 0,
            trust_level,
            aliases: Vec::new(),
            platforms: HashMap::new(),
        }
    }
}

/// In-memory registry mapping `PeerId` to `PeerProfile`.
///
/// Alias and platform lookups use a reverse index for O(1) resolution.
/// SQLite persistence is handled by `SqliteStorage` (see storage module).
#[derive(Debug, Default)]
pub struct PeerRegistry {
    peers: HashMap<PeerId, PeerProfile>,
    next_id: u64,
    /// Reverse index: any identifier (name, alias, platform username) -> PeerId.
    index: HashMap<String, PeerId>,
}

impl PeerRegistry {
    /// Create an empty registry.
    pub fn new() -> Self {
        Self::default()
    }

    /// Register a new peer and return its assigned `PeerId`.
    ///
    /// Returns `Err(Error::DuplicateAlias)` if the name is already taken.
    pub fn register_peer(
        &mut self,
        name: impl Into<String>,
        trust_level: TrustLevel,
    ) -> Result<PeerId, Error> {
        let name = name.into();
        if self.index.contains_key(&name) {
            return Err(Error::DuplicateAlias(name));
        }
        let id = PeerId(self.next_id);
        self.next_id += 1;
        self.index.insert(name.clone(), id);
        self.peers
            .insert(id, PeerProfile::new(id, name, trust_level));
        Ok(id)
    }

    /// Register a peer with a pre-assigned `PeerId` (used when loading from storage).
    ///
    /// Returns `Err(Error::DuplicateAlias)` if the name is already taken.
    pub fn register_peer_with_id(
        &mut self,
        id: PeerId,
        name: impl Into<String>,
        trust_level: TrustLevel,
    ) -> Result<(), Error> {
        let name = name.into();
        if self.index.contains_key(&name) {
            return Err(Error::DuplicateAlias(name));
        }
        if id.0 >= self.next_id {
            self.next_id = id.0 + 1;
        }
        self.index.insert(name.clone(), id);
        self.peers
            .insert(id, PeerProfile::new(id, name, trust_level));
        Ok(())
    }

    /// Restore the persisted evidence trust state for a peer (loader only).
    ///
    /// Used by storage load to recover the trust reservoir and evidence count that
    /// corroboration/feedback moved, rather than re-seeding from the coarse level.
    pub fn set_trust_state(
        &mut self,
        id: PeerId,
        trust_reservoir: f64,
        trust_evidence_count: u64,
    ) -> Result<(), Error> {
        let profile = self.peers.get_mut(&id).ok_or(Error::PeerNotFound(id))?;
        profile.trust_reservoir =
            crate::mechanics::priors::clamp_log_odds(trust_reservoir);
        profile.trust_evidence_count = trust_evidence_count;
        Ok(())
    }

    /// Resolve any identifier (name, alias, platform username) to a `PeerId`.
    pub fn resolve_peer(&self, identifier: &str) -> Option<PeerId> {
        self.index.get(identifier).copied()
    }

    /// Get a peer profile by `PeerId`.
    pub fn get_peer(&self, id: PeerId) -> Option<&PeerProfile> {
        self.peers.get(&id)
    }

    /// Get a mutable peer profile by `PeerId`.
    pub fn get_peer_mut(&mut self, id: PeerId) -> Option<&mut PeerProfile> {
        self.peers.get_mut(&id)
    }

    /// Add an alias to an existing peer.
    ///
    /// Returns `Err(Error::DuplicateAlias)` if the alias is already taken by any peer.
    pub fn add_alias(&mut self, id: PeerId, alias: impl Into<String>) -> Result<(), Error> {
        let alias = alias.into();
        if self.index.contains_key(&alias) {
            return Err(Error::DuplicateAlias(alias));
        }
        let profile = self.peers.get_mut(&id).ok_or(Error::PeerNotFound(id))?;
        profile.aliases.push(alias.clone());
        self.index.insert(alias, id);
        Ok(())
    }

    /// Add a platform username mapping to an existing peer.
    ///
    /// Returns `Err(Error::DuplicateAlias)` if the username is already taken.
    pub fn add_platform(
        &mut self,
        id: PeerId,
        platform: impl Into<String>,
        username: impl Into<String>,
    ) -> Result<(), Error> {
        let username = username.into();
        if self.index.contains_key(&username) {
            return Err(Error::DuplicateAlias(username));
        }
        let profile = self.peers.get_mut(&id).ok_or(Error::PeerNotFound(id))?;
        profile.platforms.insert(platform.into(), username.clone());
        self.index.insert(username, id);
        Ok(())
    }

    /// Set the coarse trust level of an existing peer (an explicit policy decision).
    ///
    /// This re-seeds the evidence trust reservoir to the new level's prior ONLY when
    /// no evidence has yet moved it (`trust_evidence_count == 0`); once corroboration
    /// or feedback has accumulated, the evidence estimate is preserved so a policy
    /// re-label never silently erases learned reliability.
    pub fn update_trust(&mut self, id: PeerId, trust_level: TrustLevel) -> Result<(), Error> {
        let profile = self.peers.get_mut(&id).ok_or(Error::PeerNotFound(id))?;
        profile.trust_level = trust_level;
        if profile.trust_evidence_count == 0 {
            profile.trust_reservoir = trust_level.prior_trust_reservoir();
        }
        Ok(())
    }

    /// Move a peer's evidence trust reservoir one Rescorla-Wagner step toward a
    /// signed evidence target (social.md "Peer Trust"): the single registry-level
    /// trust-evidence update path.
    ///
    /// `target` and `eta` are supplied by the engine from
    /// [`crate::mechanics::priors`] (`trust_evidence_target` /
    /// `update_trust_reservoir` / `TRUST_LEARNING_RATE`). Returns the
    /// `(old_reservoir, new_reservoir)` pair so the caller can emit a trace; the
    /// evidence count is incremented so a policy re-label never silently discards
    /// the learned estimate. Never touches `trust_level`, name, or aliases — origin
    /// and provenance are preserved (social.md: "Peer trust never erases origin").
    pub fn nudge_trust(
        &mut self,
        id: PeerId,
        target: f64,
        eta: f64,
    ) -> Result<(f64, f64), Error> {
        let profile = self.peers.get_mut(&id).ok_or(Error::PeerNotFound(id))?;
        let old = profile.trust_reservoir;
        let new = crate::mechanics::priors::update_trust_reservoir(old, target, eta);
        profile.trust_reservoir = new;
        profile.trust_evidence_count = profile.trust_evidence_count.saturating_add(1);
        Ok((old, new))
    }

    /// List all registered peers.
    pub fn list_peers(&self) -> Vec<&PeerProfile> {
        self.peers.values().collect()
    }

    /// Returns the number of registered peers.
    pub fn peer_count(&self) -> usize {
        self.peers.len()
    }

    /// Returns all identifiers for a given peer (name + aliases + platform usernames).
    pub fn all_identifiers(&self, id: PeerId) -> Vec<String> {
        let Some(profile) = self.peers.get(&id) else {
            return Vec::new();
        };
        let mut ids = vec![profile.name.clone()];
        ids.extend(profile.aliases.iter().cloned());
        ids.extend(profile.platforms.values().cloned());
        ids
    }
}
