//! Peer identity module — PeerId, PeerProfile, TrustLevel, SourceKind, PeerRegistry.
//!
//! A "peer" is any human or agent that produces knowledge fragments ingested into
//! the graph. The registry maps stable `PeerId` values to human-readable aliases
//! and platform usernames, enabling multi-agent and multi-human knowledge graphs.

use crate::error::Error;
use crate::graph::types::PeerId;
use std::collections::HashMap;

/// Trust level assigned to a peer.
///
/// Determines the `scope_weight` bonus applied during search ranking.
/// Declared lowest-to-highest so `Ord` derives correctly (Untrusted < Owner).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub enum TrustLevel {
    /// Untrusted source — penalised in ranking. scope_weight -0.05
    Untrusted,
    /// Read-only observer — can query but not contribute. scope_weight +0.00
    Observer,
    /// Automated agent — no human in the loop. scope_weight +0.00
    Agent,
    /// Standard member — regular contributor. scope_weight +0.03
    Member,
    /// Administrative trust — can manage peers and conventions. scope_weight +0.07
    Admin,
    /// Full trust — graph owner or primary operator. scope_weight +0.10
    Owner,
}

impl TrustLevel {
    /// Returns the scope_weight bonus (positive or negative) for this trust level.
    pub fn scope_weight_bonus(&self) -> f64 {
        match self {
            TrustLevel::Owner => 0.10,
            TrustLevel::Admin => 0.07,
            TrustLevel::Member => 0.03,
            TrustLevel::Agent => 0.00,
            TrustLevel::Observer => 0.00,
            TrustLevel::Untrusted => -0.05,
        }
    }
}

/// The kind of source that produced a knowledge fragment.
///
/// Consumers set this explicitly on `Origin`; the engine never auto-classifies.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum SourceKind {
    /// Observation made by an automated agent during a session.
    AgentObservation,
    /// Direct input from a human (typed message, annotation, etc.).
    HumanInput,
    /// Fact extracted from a document, file, or structured data source.
    DocumentExtract,
    /// Event generated by the system (tick, migration, lifecycle hook).
    SystemEvent,
    /// Derived or synthesised from existing graph nodes (no external source).
    Inferred,
    /// Imported from an external system or API.
    External,
}

/// Profile of a registered peer.
#[derive(Debug, Clone, PartialEq)]
pub struct PeerProfile {
    /// Stable identifier.
    pub id: PeerId,
    /// Primary display name.
    pub name: String,
    /// Trust level assigned to this peer.
    pub trust_level: TrustLevel,
    /// Additional aliases (nicknames, handles).
    pub aliases: Vec<String>,
    /// Platform to username mappings (e.g. "discord" to "ino#1234").
    pub platforms: HashMap<String, String>,
}

impl PeerProfile {
    /// Create a new profile with the given name and trust level.
    pub fn new(id: PeerId, name: impl Into<String>, trust_level: TrustLevel) -> Self {
        Self {
            id,
            name: name.into(),
            trust_level,
            aliases: Vec::new(),
            platforms: HashMap::new(),
        }
    }
}

/// In-memory registry mapping `PeerId` to `PeerProfile`.
///
/// Alias and platform lookups use a reverse index for O(1) resolution.
/// SQLite persistence is handled by `SqliteStorage` (see storage module).
#[derive(Debug, Default)]
pub struct PeerRegistry {
    peers: HashMap<PeerId, PeerProfile>,
    next_id: u64,
    /// Reverse index: any identifier (name, alias, platform username) -> PeerId.
    index: HashMap<String, PeerId>,
}

impl PeerRegistry {
    /// Create an empty registry.
    pub fn new() -> Self {
        Self::default()
    }

    /// Register a new peer and return its assigned `PeerId`.
    ///
    /// Returns `Err(Error::DuplicateAlias)` if the name is already taken.
    pub fn register_peer(
        &mut self,
        name: impl Into<String>,
        trust_level: TrustLevel,
    ) -> Result<PeerId, Error> {
        let name = name.into();
        if self.index.contains_key(&name) {
            return Err(Error::DuplicateAlias(name));
        }
        let id = PeerId(self.next_id);
        self.next_id += 1;
        self.index.insert(name.clone(), id);
        self.peers
            .insert(id, PeerProfile::new(id, name, trust_level));
        Ok(id)
    }

    /// Register a peer with a pre-assigned `PeerId` (used when loading from storage).
    ///
    /// Returns `Err(Error::DuplicateAlias)` if the name is already taken.
    pub fn register_peer_with_id(
        &mut self,
        id: PeerId,
        name: impl Into<String>,
        trust_level: TrustLevel,
    ) -> Result<(), Error> {
        let name = name.into();
        if self.index.contains_key(&name) {
            return Err(Error::DuplicateAlias(name));
        }
        if id.0 >= self.next_id {
            self.next_id = id.0 + 1;
        }
        self.index.insert(name.clone(), id);
        self.peers
            .insert(id, PeerProfile::new(id, name, trust_level));
        Ok(())
    }

    /// Resolve any identifier (name, alias, platform username) to a `PeerId`.
    pub fn resolve_peer(&self, identifier: &str) -> Option<PeerId> {
        self.index.get(identifier).copied()
    }

    /// Get a peer profile by `PeerId`.
    pub fn get_peer(&self, id: PeerId) -> Option<&PeerProfile> {
        self.peers.get(&id)
    }

    /// Get a mutable peer profile by `PeerId`.
    pub fn get_peer_mut(&mut self, id: PeerId) -> Option<&mut PeerProfile> {
        self.peers.get_mut(&id)
    }

    /// Add an alias to an existing peer.
    ///
    /// Returns `Err(Error::DuplicateAlias)` if the alias is already taken by any peer.
    pub fn add_alias(&mut self, id: PeerId, alias: impl Into<String>) -> Result<(), Error> {
        let alias = alias.into();
        if self.index.contains_key(&alias) {
            return Err(Error::DuplicateAlias(alias));
        }
        let profile = self.peers.get_mut(&id).ok_or(Error::PeerNotFound(id))?;
        profile.aliases.push(alias.clone());
        self.index.insert(alias, id);
        Ok(())
    }

    /// Add a platform username mapping to an existing peer.
    ///
    /// Returns `Err(Error::DuplicateAlias)` if the username is already taken.
    pub fn add_platform(
        &mut self,
        id: PeerId,
        platform: impl Into<String>,
        username: impl Into<String>,
    ) -> Result<(), Error> {
        let username = username.into();
        if self.index.contains_key(&username) {
            return Err(Error::DuplicateAlias(username));
        }
        let profile = self.peers.get_mut(&id).ok_or(Error::PeerNotFound(id))?;
        profile.platforms.insert(platform.into(), username.clone());
        self.index.insert(username, id);
        Ok(())
    }

    /// Update the trust level of an existing peer.
    pub fn update_trust(&mut self, id: PeerId, trust_level: TrustLevel) -> Result<(), Error> {
        let profile = self.peers.get_mut(&id).ok_or(Error::PeerNotFound(id))?;
        profile.trust_level = trust_level;
        Ok(())
    }

    /// List all registered peers.
    pub fn list_peers(&self) -> Vec<&PeerProfile> {
        self.peers.values().collect()
    }

    /// Returns the number of registered peers.
    pub fn peer_count(&self) -> usize {
        self.peers.len()
    }

    /// Returns all identifiers for a given peer (name + aliases + platform usernames).
    pub fn all_identifiers(&self, id: PeerId) -> Vec<String> {
        let Some(profile) = self.peers.get(&id) else {
            return Vec::new();
        };
        let mut ids = vec![profile.name.clone()];
        ids.extend(profile.aliases.iter().cloned());
        ids.extend(profile.platforms.values().cloned());
        ids
    }
}
